### ISSUE TITLE
Details of KNN classifier for ImageNet-LT

### ISSUE THREAD

**Issue by thss15fyt** [frank-xwang/CLD-UnsupervisedLearning#10]
Thanks for your interesting work!

I would like to know some details of how you perform kNN classifier on the ImageNet-LT dataset, including the number of K and the temperature used in exp(cos_sim / t). Besides, which set of the dataset (train, validation or both) is used to be the support set to search for kNN? Thanks!

**Comment by frank-xwang** [comment]
Hi, for KNN classifier on ImageNet-LT, we used the support set from training set and use the same number of K and temperature as in the experiment on ImageNet. Sorry for the late reply
