### ISSUE TITLE
Using CLD in barlow twins method

### ISSUE THREAD

**Issue by EBGU** [frank-xwang/CLD-UnsupervisedLearning#3]
Hi!

I am currently learning SSL, and I found your code very helpful! I wonder if your CLD method could work for barlow twins (https://github.com/facebookresearch/barlowtwins)? In theory yes, but barlow twins take the advantage of high-dimension embedding and your method has to cluster all features in a low-dimension space. I understood that those are in different branches and may not interfere with each other, but I am not very sure about that. Also, barlow twins scale its loss to a large number, which could also cause incompatible problems.

Thx!

**Comment by EBGU** [comment]
I am currently training a network combining your CLD with barlowtwins. The initial loss of barlow twins is around 10^4 and the initial loss of your CLD is around 4. What I do is that scale CLD loss similar to barlow twins. I only have one RTX3090, so it would take time to see if it would work out.

**Comment by frank-xwang** [comment]
Hi, good to know that you are trying to combine CLD with BarLowTwins! My concern is also on the high feature dimension, which may cause the low clustering quality. Maybe it is necessary to have a projection layer to project the high-dimensional feature space to a low-dimensional one.
