### ISSUE TITLE
BYOL+CLD

### ISSUE THREAD

**Issue by EBGU** [frank-xwang/CLD-UnsupervisedLearning#6]
Hi!

I am currently working with your proposed CLD loss in BYOL. I found your paper and your code really helpful! I wonder if I should use the detached output from the target encoder when calculating CLD loss in BYOL to stop gradients? Thank you!

**Comment by frank-xwang** [comment]
Thanks! For your question, it is not necessary to use the target encoder with stop gradients to calculate the CLD loss.
