### ISSUE TITLE
Accuracy error

### ISSUE THREAD

**Issue by xcvil** [frank-xwang/CLD-UnsupervisedLearning#7]
Hi Wang!

Thanks for your code again!

When I tried to train with the cld+moco, I got errors.

File "./main_imagenet_moco_cld.py", line 493, in accuracy
```
    correct_k = correct[:k].view(-1).float().sum(0, keepdim=True)
```
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by frank-xwang** [comment]
Hi Xiaochen, I tried to run the code on my server and it seems to work well. I am using Python==3.7.9, pytorch=="1.6.0+cu101" and torchvision==0.7.0+cu101'. You can try to upgrade or downgrade the pytorch/torchvision version to the version I am using.
![Screen Shot 2021-05-13 at 7 26 03 PM](https://user-images.githubusercontent.com/58996472/118211503-112cc800-b421-11eb-89ec-2e98a8990eec.png)
In addition, you can also try adding .contiguous() before .view() to get rid of the bug. But I suggest you to double check the pytorch/torchvision version first.
